<?php

/**
 * @file
 * Contains milestone.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function milestone_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the milestone module.
    case 'help.page.milestone':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function milestone_theme() {
  $theme = [];
  $theme['milestone'] = [
    'render element' => 'elements',
    'file' => 'milestone.page.inc',
    'template' => 'milestone',
  ];
  $theme['milestone_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'milestone.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function milestone_theme_suggestions_milestone(array $variables) {
  $suggestions = array();
  $entity = $variables['elements']['#milestone'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'milestone__' . $sanitized_view_mode;
  $suggestions[] = 'milestone__' . $entity->bundle();
  $suggestions[] = 'milestone__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'milestone__' . $entity->id();
  $suggestions[] = 'milestone__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
