<?php

/**
 * @file
 * Contains task_manager.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function task_manager_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the task_manager module.
    case 'help.page.task_manager':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function task_manager_theme() {
  $theme = [];
  $theme['project'] = [
    'render element' => 'elements',
    'file' => 'project.page.inc',
    'template' => 'project',
  ];
  $theme['project_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'project.page.inc',
  ];
  $theme['task'] = array(
     'render element' => 'elements',
     'file' => 'task.page.inc',
     'template' => 'task',
   );
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function task_manager_theme_suggestions_project(array $variables) {
  $suggestions = array();
  $entity = $variables['elements']['#project'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'project__' . $sanitized_view_mode;
  $suggestions[] = 'project__' . $entity->bundle();
  $suggestions[] = 'project__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'project__' . $entity->id();
  $suggestions[] = 'project__' . $entity->id() . '__' . $sanitized_view_mode;

  return $suggestions;
}
