module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  config: 0
  datetime: 0
  dblog: 0
  devel: 0
  dynamic_page_cache: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  image: 0
  kint: 0
  link: 0
  menu_link_content: 0
  menu_ui: 0
  milestone: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  project: 0
  responsive_image: 0
  system: 0
  task: 0
  task_manager: 0
  text: 0
  toolbar: 0
  user: 0
  views: 0
  views_ui: 0
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
